version: '3.1'
services:
 embeddings:
    container_name: embeddings
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./pipeline/Dockerfile.nodejs-dev
      args:
        - APP_NAME=embeddings
    environment:
      env: dev
      HOST: '0.0.0.0'
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - gpt-nx
    volumes:
      - ./dist/apps/embeddings:/usr/app/dist
networks:
  gpt-nx:
    name: gpt-nx
    driver: bridge
